name: tampilan_ukk
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  intl: ^0.19.0
  pdf: ^3.10.0
  printing: ^5.11.0
  path_provider: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

